local root = _MAIN_SCRIPT_DIR

-- Embed ant.png into a header so there is no working-directory or post-build copy dependency.
local function embed(inFile, outFile, symbol)
    local data  = assert(io.readfile(inFile), "cannot read " .. inFile)
    local lines = {}
    for i = 1, #data, 24 do
        local row = {}
        for j = i, math.min(i + 23, #data) do row[#row + 1] = data:byte(j) end
        lines[#lines + 1] = "    " .. table.concat(row, ",") .. ","
    end
    os.mkdir(path.getdirectory(outFile))
    io.writefile(outFile, table.concat({
        "// Generated by premake5 from " .. path.getname(inFile) .. ". Do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "inline constexpr unsigned char " .. symbol .. "[] = {",
        table.concat(lines, "\n"),
        "};",
        "inline constexpr std::size_t " .. symbol .. "Size = sizeof(" .. symbol .. ");",
        ""
    }, "\n"))
end
embed(root .. "/Resources/ant.png", root .. "/generated/include/AntPng.hpp", "AntPng")

workspace "LangtonsAnt"
    configurations { "Debug", "Release" }
    startproject "LangtonsAnt"
    location "build"
    cppdialect "C++20"
    warnings "Extra"
    defines { "SFML_STATIC" }
    targetdir (root .. "/bin/%{cfg.buildcfg}-%{cfg.system}")
    objdir    (root .. "/bin-int/%{cfg.buildcfg}-%{cfg.system}/%{prj.name}")

    filter "system:windows or system:linux"
        architecture "x86_64"
    filter "configurations:Debug"
        symbols "On"
    filter "configurations:Release"
        optimize "On"
        defines { "NDEBUG" }
    filter {}

    include "vendor/freetype.lua"
    include "vendor/sfml.lua"

project "LangtonsAnt"
    kind "ConsoleApp"
    language "C++"
    files { "src/**.cpp", "include/**.hpp" }
    includedirs { "include", "generated/include", "vendor/SFML/include" }
    links { "sfml-graphics", "sfml-window", "sfml-system", "freetype" }

    filter "system:windows"
        links { "opengl32", "winmm", "gdi32" }
    filter { "system:windows", "toolset:gcc" }
        linkoptions { "-static", "-Wl,-Bstatic,--whole-archive", "-lwinpthread", "-Wl,--no-whole-archive" }
    filter "system:linux"
        links { "X11", "Xrandr", "Xcursor", "Xi", "udev", "GL", "dl", "pthread" }
        linkoptions { "-static-libstdc++", "-static-libgcc" }
    filter "system:macosx"
        links { "Cocoa.framework", "IOKit.framework", "OpenGL.framework", "Carbon.framework" }
    filter {}
